def call() {
  echo "runTest"
  error "FAIL 1"
}
